<?php
namespace app\admin\controller;
use think\Controller;
use think\Db;

class Base extends Controller
{
    /**
     * @var array 指定其他方法执行前的操作（方法）
     */
    protected $beforeActionList = [
//        指定before为其他方法的前置方法
        'before'
    ];

    /**
     * @return bool|mixed
     * @desc 检测是否登陆
     */
    public function before()
    {
        if (session('username')){
            return true;
        }
        else{
            $this->redirect('site/login');
        }
 //        return parent::beforeAction($method, $options); // TODO: Change the autogenerated stub
    }
//    public function test(){
//        echo 'test';
//        return config('database.type');
//        Db::table('');
//        Db::query('');#原生sql
//    }
}