<?php
namespace app\admin\controller;
use think\Controller;
use think\Db;

class Base extends Controller
{
    protected $beforeActionList = [
//        指定before为其他方法的前置方法
        'before'
    ];
    public function before()
    {
        if (session('username')){
            return true;
        }
        else{
            return $this->fetch('site/login.html');
        }
 //        return parent::beforeAction($method, $options); // TODO: Change the autogenerated stub
    }
//    public function test(){
//        echo 'test';
//        return config('database.type');
//        Db::table('');
//        Db::query('');#原生sql
//    }
}